### ISSUE TITLE
Missing "unzip" in the silva classifier step

### ISSUE THREAD

**Issue by d4straub** [nf-core/rrna-ampliseq#35]
Process make_SILVA_132_16S_classifier slipped our test runs. 
Test command for fast processing e.g.:
`nextflow run rrna-ampliseq -profile test,singularity --classifier false --dereplication 90`

from #33

**Comment by d4straub** [comment]
removed obvious problems but `unzip` still doesnt work

**Comment by apeltzer** [comment]
That just requires to add `conda-forge::unzip=6.0` to our `environment.yaml` and we're all good :-)

**Comment by d4straub** [comment]
works when I use my QIIME2 conda environment, but doesnt work with `--profile singularity`:
.command.sh: line 2: unzip: command not found

**Comment by d4straub** [comment]
Locally with recently pulled github repo, deleted folders work and .nextflow and run 

`nextflow run rrna-ampliseq -profile test,singularity --classifier false --dereplication 90 --skip_fastqc --skip_ancom --skip_diversity_indices --skip_alpha_rarefaction` 

but still ".command.sh: line 2: unzip: command not found"

**Comment by apeltzer** [comment]
Super weird, restarted the docker cloud build.

**Comment by apeltzer** [comment]
Ah, I see - pipeline uses latest, change is only present on `dev`. 
I'm pushing to `master` to force a container update here as well and then we're good :-)

**Comment by apeltzer** [comment]
This fixes the issue locally - test it on the cluster and let me know how it goes :-)

**Comment by apeltzer** [comment]
Build finished, testing works and unzip is found :-)
