### ISSUE TITLE
Read Input Parameter as Folder

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rrna-ampliseq#8]
params.reads should only specify the folder, but only files like *_L001_R{1,2}_001.fastq.gz are chosen (QIIME2 PE input requires *_L001_R{1,2}_001.fastq.gz format, so this is required anyway)

**Comment by d4straub** [comment]
This doesnt work with 1.0dev. I still need to define --reads "data/*_L001_R{1,2}_001.fastq.gz" 
In branch dev I somehow cant find the changes you made in main.nf, but the changes in nextflow.config are present.

**Comment by d4straub** [comment]
also, all --singleEnd options would not work at the moment. `qiime import` is expecting paired end, we would need to implement single end processing in several steps.

**Comment by d4straub** [comment]
works
