### ISSUE TITLE
LogFile with some features

### ISSUE THREAD

**Issue by apeltzer** [nf-core/rrna-ampliseq#9]
make nice looking log with stuff written currently to stdout ("echo" etc.)

**Comment by apeltzer** [comment]
Maybe in `workflow.onComplete`?

**Comment by d4straub** [comment]
Going to try out log.info as in https://github.com/nf-core/rnaseq/blob/master/main.nf line 539

**Comment by d4straub** [comment]
still to do:
- error message if dada_trunc values are too small in process dada_trunc_parameter
- warning if rarefaction depth is too low in process diversity_core

**Comment by d4straub** [comment]
done
